### ISSUE TITLE
Porting Project to asi format ScripthookV

### ISSUE THREAD

**Issue by j1m1l0k0** [CamxxCore/TornadoScript#3]
Would it be very laborious to port C # to C ++? this would not depend on ScripthookDotnet and could run the script in.

**Comment by CamxxCore** [comment]
It could certainly be done. And would not be too difficult! The only point of difficulty I can see would be porting some of the memory- related functions over. The conversion of such things might be confusing if you are not familiar with the concepts, of structure layout in memory and converting the pointers to the native counterpart. I'm looking for some new projects to work on so I may be able to assist should you take this on!

**Comment by j1m1l0k0** [comment]
The idea was to port his project to make it compatible with FiveM. It would be so much fun watching your tornado making the players and everything on the front flying to the top LOL

What part of the memory conversion do you say?

**Comment by CamxxCore** [comment]
Well if its for FiveM those parts of the code can probably be omitted entirely. But naturally it may cause more FPS- drops when you are using the scripted API vs. grabbing the entity array directly in memory. The secondary issue is the LOD- distance on the particles, it can only be changed manually/ internally. Obviously this would be a client- side effect only, so useless in FiveM.

**Comment by j1m1l0k0** [comment]
humm ok

**Comment by j1m1l0k0** [comment]
Are you interested in projects for other American Truck Simulator type games? There is currently a very bad mod for this game.

This game needs somebody with enough knowledge in reverse engineering, because they say that it is very complex to reverse.

**Comment by CamxxCore** [comment]
I can’t say I took an interest in this particular game. If there is some information online already maybe I can build on it and do something. What kind of mods are you looking for?

**Comment by j1m1l0k0** [comment]
In fact, there is a multiplayer mod for this game, but very poorly developed. the idea was an improved multiplayer system than already exists.Something simple client / server

**Comment by j1m1l0k0** [comment]
I thought a mod even in the gta5 itself, because there are trucks that were freight delivery, freight and things like I could not think of anything creative.
